  CREATE TABLE `goods` (
    `id` int NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `biz_id` varchar(32) NOT NULL COMMENT 'spuid',
    `category_id` varchar(32) NOT NULL COMMENT '叶子类目id',
    `barcode` varchar(32) DEFAULT NULL COMMENT '条形码',
    `code` varchar(32) NOT NULL DEFAULT '' COMMENT '商品编码',
    `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '名称',
    `short_name` varchar(128) DEFAULT NULL COMMENT '商品简称',
    `pinyin` varchar(128) DEFAULT NULL COMMENT '汉字的首字符简拼',
    `unit_name` varchar(32) DEFAULT NULL COMMENT '单位(个,份,瓶)',
    `cover_image` varchar(255) DEFAULT NULL COMMENT '商品主图',
    `description` varchar(1024) DEFAULT NULL COMMENT '详情介绍',
    `image_list` varchar(1024) DEFAULT NULL COMMENT '图片列表',
    `generic_attr` varchar(512) DEFAULT NULL COMMENT '通用属性(用于显示描述)',
    `special_attr` text COMMENT '规格属性',
    `tag_str` json DEFAULT NULL COMMENT '商品标签 {"新品","热销"}',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态(0:正常 1:已失效)',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记(0:正常 1:已删除)',
    `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
    `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `creator_id` varchar(32) NOT NULL COMMENT '创建人ID',
    `creator_name` varchar(32) NOT NULL COMMENT '创建人名字',
    `operator_id` varchar(32) NOT NULL COMMENT '修改人ID',
    `operator_name` varchar(32) NOT NULL COMMENT '修改人名字',
    PRIMARY KEY (`id`),
  ) ENGINE=InnoDB AUTO_INCREMENT=569 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品SPU';


  CREATE TABLE `order` (
    `id` int NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `biz_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '业务主键',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT '0:待支付 1:已取消 2:支付超时 3:已支付 4:已退单',
    `channel_status` int DEFAULT '0' COMMENT '渠道原始订单状态',
    `brand_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '品牌id',
    `store_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '门店ID',
    `user_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '会员ID(可为空)',
    `user_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
    `user_open_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
    `invoice_status` tinyint NOT NULL DEFAULT '0' COMMENT '开票状态 0:未开票 1:开票成功 2:开票中 3:撤销开票',
    `preferential_info` json DEFAULT NULL COMMENT '优惠详情(json格式)',
    `total_quantity` int NOT NULL COMMENT '商品总数',
    `total_amount` decimal(10,2) NOT NULL COMMENT '商品总额',
    `actual_amount` decimal(10,2) NOT NULL COMMENT '应收金额',
    `pay_amount` decimal(10,2) NOT NULL COMMENT '实收金额(抹零之后的金额)',
    `pay_method` int DEFAULT '0' COMMENT '支付方式',
    `confirmed` tinyint(1) NOT NULL DEFAULT '1' COMMENT '定单是否确认',
    `refund_status` tinyint DEFAULT '0',
    `pay_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '支付时间',
    `transaction_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
    `origin_transaction_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '渠道交易流水号',
    `remark` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '订单备注',
    `refunded_quantity` int DEFAULT '0',
    `refunded_amount` decimal(10,2) DEFAULT '0.00',
    `actual_refunded_amount` decimal(10,2) DEFAULT '0.00',
    `origin_info` json DEFAULT NULL COMMENT '渠道原始订单信息',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记(0:正常 1:已删除)',
    `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
    `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `creator_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '创建人ID',
    `creator_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '创建人名字',
    `updated_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `operator_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '修改人ID',
    `operator_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '修改人名字',
    `order_type` int DEFAULT NULL COMMENT '是否是消费订单(1:消费订单 2:充值储值订单)',
    PRIMARY KEY (`id`),
  ) ENGINE=InnoDB AUTO_INCREMENT=1968 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单信息';




  CREATE TABLE `user_wechat` (
    `id` int NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `biz_id` varchar(32) NOT NULL COMMENT '业务主键',
    `user_id` varchar(32) NOT NULL COMMENT '用户id',
    `member_code` varchar(32) NOT NULL COMMENT '会员码',
    `token` varchar(255) NOT NULL DEFAULT '' COMMENT '用户Token',
    `nick_name` varchar(255) NOT NULL DEFAULT '' COMMENT '用户昵称',
    `phone` varchar(255) NOT NULL DEFAULT '' COMMENT '用户手机号码',
    `gender` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '用户性别(0:未知, 1:男性, 2:女性)',
    `birthday` date DEFAULT NULL COMMENT '生日',
    `avatar_url` varchar(255) NOT NULL DEFAULT '' COMMENT '用户头像图片URL',
    `country` varchar(255) NOT NULL DEFAULT '' COMMENT '用户所在国家',
    `province` varchar(255) NOT NULL DEFAULT '' COMMENT '用户所在省份',
    `city` varchar(255) NOT NULL DEFAULT '' COMMENT '用户所在城市',
    `extend_info` varchar(2048) DEFAULT '' COMMENT '扩展信息（JSON）',
    `source` tinyint DEFAULT NULL COMMENT '来源: 1:微信 2:手工填写 ',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记(0:正常 1:已删除)',
    `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
    `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `creator_id` varchar(32) NOT NULL COMMENT '创建人ID',
    `creator_name` varchar(32) NOT NULL COMMENT '创建人名字',
    `operator_id` varchar(32) NOT NULL COMMENT '修改人ID',
    `operator_name` varchar(32) NOT NULL COMMENT '修改人名字',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_open_id` (`open_id`) USING BTREE,

  ) ENGINE=InnoDB AUTO_INCREMENT=58 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户微信信息表';




